version: "3.8"
name: jardin_landingpage
services:
  prod:
    container_name: jardin_landingpage
    image: jardin_landingpage:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: bash -c "npm install && npm run start:prod"
    restart: always
    env_file: .env
    environment:
      - PORT=80
    ports:
      - ${LANDINGPAGE_PORT}:80
    volumes:
      - ./landingpage:/app
    extra_hosts:
      - host.docker.internal:host-gateway
